version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/todo_app:latest .
            docker push $DOCKERHUB_USERNAME/todo_app:latest
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Configure gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud container clusters get-credentials whizlabs-cluster --zone us-central1-a --project $GCLOUD_PROJECT_ID
      - run:
          name: Deploy to Kubernetes
          command: kubectl apply -f Deployment.yaml
  when: << pipeline.parameters.build.result == 'success' >>
workflows:
  build-and-deploy:
    jobs:
      - build:
          context: my-context
      - deploy:
          context: my-context
